"""Centralized runner and session orchestration for Google ADK agents."""

from __future__ import annotations

import uuid
from typing import Any
from google.adk.agents import Agent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.genai import types


async def get_runner(
    root_agent: Agent,
    app_name: str = "agent_patterns",
    user_id: str = "user_1",
    session_id: str | None = None,
) -> tuple[Runner, str, str]:
    """Initializes an in-memory session service and ADK Runner.

    Args:
        root_agent: The root Agent or composite agent (Sequential, Parallel, Loop).
        app_name: Application namespace identifier.
        user_id: Identifier for the current user.
        session_id: Unique session identifier; defaults to a generated UUID string.

    Returns:
        A tuple of (runner, user_id, session_id).
    """
    resolved_session_id = session_id or f"session_{uuid.uuid4().hex[:8]}"
    session_service = InMemorySessionService()

    await session_service.create_session(
        app_name=app_name,
        user_id=user_id,
        session_id=resolved_session_id,
    )

    runner = Runner(
        agent=root_agent,
        app_name=app_name,
        session_service=session_service,
    )

    return runner, user_id, resolved_session_id


async def call_agent_async(
    query: str,
    runner: Runner,
    user_id: str,
    session_id: str,
) -> str:
    """Executes a turn in the conversation and streams events to the final response.

    Args:
        query: User input prompt.
        runner: ADK Runner orchestrating execution.
        user_id: The active user ID.
        session_id: The active session ID.

    Returns:
        The final response text generated by the agent pipeline.
    """
    print(f"\n>>> User Query: {query}")
    content = types.Content(role="user", parts=[types.Part(text=query)])
    final_response_text = "Agent did not produce a final response."

    async for event in runner.run_async(
        user_id=user_id,
        session_id=session_id,
        new_message=content,
    ):
        if event.is_final_response():
            if event.content and event.content.parts:
                final_response_text = event.content.parts[0].text
            elif event.actions and event.actions.escalate:
                err_msg = getattr(event, "error_message", None) or "No specific message."
                final_response_text = f"Agent escalated: {err_msg}"
            break

    print(f"<<< Agent Response:\n{final_response_text}\n")
    return final_response_text
